version: '3.3'

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: dev.Dockerfile
    image: nginx    
    container_name: nginx
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    links:
      - client
      - server
    ports:
      - 80:80
      - 8080:80

  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    image: client
    container_name: client
    volumes:
      - ./client/:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - server:server
    depends_on:
      - server
    expose:
      - 8080

  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    image: server
    container_name: server
    volumes:
      - ./server/:/usr/src/api/
      - /usr/src/api/node_modules
    env_file: ./server/.env
    links:
      - mongo:mongo
    depends_on:
      - mongo
    expose:
      - 3000
  
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo/:/data/
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - 27017
    command: mongod

  # elk:
  #   image: sebp/elk:latest
  #   container_name: elk
  #   expose:
  #     - 5601
  #     - 9200
  #     - 5044
