version: '3.3'

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   links:
  #       - client
  #       - server
  #       - mongo
  #       - elk
  #   ports:
  #       - 80:80
  #       - 443:433

  #       - 3000:3000
  #       - 8080:8080
  
  #       - 27017:27017
  
  #       - 5601:5601
  #       - 9200:9200
  #       - 5044:5044

  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    image: client
    container_name: client
    volumes:
      - ./client/:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - mongo:mongo
    depends_on:
      - server
    
    ports:
      - 8080:8080
    # expose:
    #   - 8080

  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    image: server
    container_name: server
    volumes:
      - ./server/:/usr/src/api/
      - /usr/src/api/node_modules
    env_file: ./server/.env
    depends_on:
      - mongo
    links:
      - mongo:mongo
    
    ports:
      - 3000:3000
    # expose:
    #   - 8080
  
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo/:/data/
    healthcheck:
      test: ["CMD", "echo", "show dbs", "|", "mongo"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - 27017
    command: mongod

  # elk:
  #   image: sebp/elk:latest
  #   container_name: elk
  #   expose:
  #     - 5601
  #     - 9200
  #     - 5044
